### PR TITLE
Fixing tar output

### PR DESCRIPTION
**Pull request by R-Lawton**

### CODE REVIEW

**Comment by reetika-vyas** [comment]
Build is successful 
```
18:20:50 Step 28/29 : RUN rm /root/anaconda* /root/original-ks.cfg
18:20:50  ---> Running in 86991435bdcf
18:20:50 Removing intermediate container 86991435bdcf
18:20:51  ---> 78a6c1fb9e33
18:20:51 Step 29/29 : WORKDIR /root
18:20:51  ---> Running in 39d7d1952346
18:20:51 Removing intermediate container 39d7d1952346
18:20:51  ---> 53b90398f836
18:20:51 Successfully built 53b90398f836
18:20:51 Successfully tagged quay.io/app-sre/managed-scripts:e1784bf
18:20:51 /usr/bin/docker tag quay.io/app-sre/managed-scripts:e1784bf quay.io/app-sre/managed-scripts:latest
18:20:51 [openshift-managed-scripts-gh-pr-check] $ /bin/sh -xe /tmp/jenkins3825402766060996190.sh
18:20:51 + '[' -z '' ']'
18:20:51 + exit
18:20:51 Setting status of b63f94083aa971d6fd995db9b0853d0e0ef8a8c0 to SUCCESS with url https://ci.ext.devshift.net/job/openshift-managed-scripts-gh-pr-check/246/ and message: ' '
18:20:51 Using context: ci.ext.devshift.net PR build
18:20:51 Finished: SUCCESS
```

**Comment by R-Lawton** [comment]
@reetika-vyas Is this ok to be merged?

**Comment by georgettica** [comment]
I think the /approve is the harder gate you need to pass
so 
/lgtm
and it should auto merge

**Comment by fahlmant** [comment]
Can you please add a description to this?

**Comment by jharrington22** [comment]
@R-Lawton @georgettica could ensure when creating PR's we have a description describing the change? Is this related to an ticket? Please link the ticket and update the description.

**Comment by georgettica** [comment]
sorry for pushing forward without verifying the Description is there. I will keep track of this aswell

**Pull request merged**
