### PR TITLE
WIP RHOSAK managed script

### PR DESCRIPTION
**Pull request by R-Lawton**

### CODE REVIEW

**Comment by georgettica** [comment]
@clcollins @R-Lawton as this PR might have exposed docker logs (means we need to fail to commit if files like this exist?

**Comment by R-Lawton** [comment]
> @clcollins @R-Lawton as this PR might have exposed docker logs (means we need to fail to commit if files like this exist?
Apologies Removed the output and rebased

**Review by georgettica — COMMENTED** [review]
Needs some more polish and maybe to make sure the code compiles and you will be on track for merging

**Comment by R-Lawton** [comment]
Thank you for the early review i will make those changes but its still a WIP and not ready yet

**Comment by georgettica** [comment]
@R-Lawton to make it clearer, you can set the PR as a draft
You're welcome

**Pull request closed without merging**
