### PR TITLE
adding  reetika  to maintainer

### PR DESCRIPTION
**Pull request by reetika-vyas**

### CODE REVIEW

**Comment by wanghaoran1988** [comment]
Could you add to reviewer & approver instead of maitainer?

**Comment by reetika-vyas** [comment]
> Could you add to reviewer & approver instead of maitainer?

yes, added and removed from maintainer

**Comment by georgettica** [comment]
@reetika-vyas did you mean to close this?

**Comment by reetika-vyas** [comment]
> @reetika-vyas did you mean to close this?
yes, I have added myself as approver here instead of maintainer

**Pull request merged**
