### PR TITLE
OSD-19603: Script to drain and reboot node without elevation

### PR DESCRIPTION
**Pull request by Dee-6777**
### What type of PR is this?

_feature_

### What this PR does / Why we need it?
It will help drain and reboot nodes without elevation thus reducing the no of compliance tickets generated due to draining

### Which Jira/Github issue(s) does this PR fix?

_Resolves_ #[OSD-19603](https://issues.redhat.com/browse/OSD-19603)

### Pre-checks (if applicable)

- [X] Validated the changes in a cluster
- [X] Included documentation changes with PR

### CODE REVIEW

**Comment by xiaoyu74** [comment]
@Dee-6777  - The logic of the script looks good to me, however, I assume you might not be able to test to validate the managed-script by creating `managedjob` in a staging cluster since this PR hasn't been merged and backplane-api will always pull the `managed-scripts` repo from the **main branch** of the repo.

Have you tested to create a `testjob` against a staging cluster instead to validate ?

**Comment by Dee-6777** [comment]
> @Dee-6777 - The logic of the script looks good to me, however, I assume you might not be able to test to validate the managed-script by creating `managedjob` in a staging cluster since this PR hasn't been merged and backplane-api will always pull the `managed-scripts` repo from the **main branch** of the repo.
> 
> Have you tested to create a `testjob` against a staging cluster instead to validate?
Hi @xiaoyu74 I created a testjob and tested it in a staging cluster

**Comment by xiaoyu74** [comment]
> > @Dee-6777 - The logic of the script looks good to me, however, I assume you might not be able to test to validate the managed-script by creating `managedjob` in a staging cluster since this PR hasn't been merged and backplane-api will always pull the `managed-scripts` repo from the **main branch** of the repo.
> > Have you tested to create a `testjob` against a staging cluster instead to validate?
> 
> Hi @xiaoyu74 I created a testjob and tested it in a staging cluster

Ok, if your tested via testjob and it works as expected, than LGTM.

**Comment by Dee-6777** [comment]
Logs for the following script
```
[dmaharan@dmaharan node-drain-reboot]$ ocmbp testjob create -p node=ip-10-0-36-113.ec2.internal 
WARN[0000] Manual URL configuration is deprecated, please remove URL key from Backplane configuration 
WARN[0001] Manual URL configuration is deprecated, please remove URL key from Backplane configuration 

        Test job openshift-job-dev-xq988 created successfully

        Run "ocm backplane testjob get openshift-job-dev-xq988" for details
        Run "ocm backplane testjob logs openshift-job-dev-xq988" for job logs

TestId: openshift-job-dev-xq988
[dmaharan@dmaharan node-drain-reboot]$ ocm backplane testjob logs openshift-job-dev-xq988
WARN[0000] Manual URL configuration is deprecated, please remove URL key from Backplane configuration 
WARN[0001] Manual URL configuration is deprecated, please remove URL key from Backplane configuration 
VALIDATING INPUT CHECKING IF CORRECT NODE IS PROVIDED..
NODE ip-10-0-36-113.ec2.internal IS PROVIDED...
NAME                          STATUS   ROLES    AGE    VERSION
ip-10-0-36-113.ec2.internal   Ready    worker   106m   v1.27.8+4fab27b
DRAINING NODE..
node/ip-10-0-36-113.ec2.internal cordoned
node/ip-10-0-36-113.ec2.internal already cordoned
Warning: ignoring DaemonSet-managed Pods: openshift-cluster-csi-drivers/aws-ebs-csi-driver-node-cpn4w, openshift-cluster-node-tuning-operator/tuned-svqz2, openshift-dns/dns-default-7m4h9, openshift-dns/node-resolver-kcpml, openshift-image-registry/node-ca-nh5r2, openshift-ingress-canary/ingress-canary-dwcxm, openshift-machine-config-operator/machine-config-daemon-7hrtm, openshift-monitoring/node-exporter-lpn7z, openshift-multus/multus-additional-cni-plugins-zctd4, openshift-multus/multus-jp2n2, openshift-multus/network-metrics-daemon-mvkrg, openshift-network-diagnostics/network-check-target-67hln, openshift-ovn-kubernetes/ovnkube-node-p489w, openshift-security/splunkforwarder-ds-q5l8c
evicting pod openshift-operator-lifecycle-manager/collect-profiles-28423275-w4585
evicting pod openshift-image-registry/image-pruner-28423260-pzthz
evicting pod openshift-operator-lifecycle-manager/collect-profiles-28423245-hjg66
pod/collect-profiles-28423245-hjg66 evicted
pod/image-pruner-28423260-pzthz evicted
pod/collect-profiles-28423275-w4585 evicted
node/ip-10-0-36-113.ec2.internal drained
REBOOTING NODE..
VERIFYING IF NODES ARE NOW IN READY STATE..
NODES ARE NOW READY. UNCORDING..
Starting pod/ip-10-0-36-113ec2internal-debug-h26nw ...
To use host binaries, run `chroot /host`
node/ip-10-0-36-113.ec2.internal uncordoned
Succeed.
```

**Comment by xiaoyu74** [comment]
> Logs for the following script
> 
> ```
> [dmaharan@dmaharan node-drain-reboot]$ ocmbp testjob create -p node=ip-10-0-36-113.ec2.internal 
> WARN[0000] Manual URL configuration is deprecated, please remove URL key from Backplane configuration 
> WARN[0001] Manual URL configuration is deprecated, please remove URL key from Backplane configuration 
> 
>         Test job openshift-job-dev-xq988 created successfully
> 
>         Run "ocm backplane testjob get openshift-job-dev-xq988" for details
>         Run "ocm backplane testjob logs openshift-job-dev-xq988" for job logs
> 
> TestId: openshift-job-dev-xq988
> [dmaharan@dmaharan node-drain-reboot]$ ocm backplane testjob logs openshift-job-dev-xq988
> WARN[0000] Manual URL configuration is deprecated, please remove URL key from Backplane configuration 
> WARN[0001] Manual URL configuration is deprecated, please remove URL key from Backplane configuration 
> VALIDATING INPUT CHECKING IF CORRECT NODE IS PROVIDED..
> NODE ip-10-0-36-113.ec2.internal IS PROVIDED...
> NAME                          STATUS   ROLES    AGE    VERSION
> ip-10-0-36-113.ec2.internal   Ready    worker   106m   v1.27.8+4fab27b
> DRAINING NODE..
> node/ip-10-0-36-113.ec2.internal cordoned
> node/ip-10-0-36-113.ec2.internal already cordoned
> Warning: ignoring DaemonSet-managed Pods: openshift-cluster-csi-drivers/aws-ebs-csi-driver-node-cpn4w, openshift-cluster-node-tuning-operator/tuned-svqz2, openshift-dns/dns-default-7m4h9, openshift-dns/node-resolver-kcpml, openshift-image-registry/node-ca-nh5r2, openshift-ingress-canary/ingress-canary-dwcxm, openshift-machine-config-operator/machine-config-daemon-7hrtm, openshift-monitoring/node-exporter-lpn7z, openshift-multus/multus-additional-cni-plugins-zctd4, openshift-multus/multus-jp2n2, openshift-multus/network-metrics-daemon-mvkrg, openshift-network-diagnostics/network-check-target-67hln, openshift-ovn-kubernetes/ovnkube-node-p489w, openshift-security/splunkforwarder-ds-q5l8c
> evicting pod openshift-operator-lifecycle-manager/collect-profiles-28423275-w4585
> evicting pod openshift-image-registry/image-pruner-28423260-pzthz
> evicting pod openshift-operator-lifecycle-manager/collect-profiles-28423245-hjg66
> pod/collect-profiles-28423245-hjg66 evicted
> pod/image-pruner-28423260-pzthz evicted
> pod/collect-profiles-28423275-w4585 evicted
> node/ip-10-0-36-113.ec2.internal drained
> REBOOTING NODE..
> VERIFYING IF NODES ARE NOW IN READY STATE..
> NODES ARE NOW READY. UNCORDING..
> Starting pod/ip-10-0-36-113ec2internal-debug-h26nw ...
> To use host binaries, run `chroot /host`
> node/ip-10-0-36-113.ec2.internal uncordoned
> Succeed.
> ```

Thank you for providing  the `testjob` logs and great work @Dee-6777 :+1:

**Comment by jaybeeunix** [comment]
it looks good to me too, as it doesn't override any pdbs.

**Pull request merged**
