### PR TITLE
[MTSRE-870] creating backplane permissions to perform full blown OLM dance

### PR DESCRIPTION
**Pull request by Ankit152**
Signed-off-by: Ankit Kurmi <akurmi@redhat.com>

### CODE REVIEW

**Comment by MitaliBhalla** [comment]
@Ankit152 Do you have an OHSS card tracking this somewhere?

**Comment by Ankit152** [comment]
Not exactly @MitaliBhalla 
If you want some context behind this PR, please feel free to have a look here: https://github.com/openshift/managed-cluster-config/pull/1402
Jira: [MTSRE-870](issues.redhat.com/browse/MTSRE-870)

**Comment by MitaliBhalla** [comment]
/lgtm from my side as I see @cblecker 's comment on the PR you linked. Hence, we can extend this permission to MT-SRE.
cc : @feichashao @wanghaoran1988 for final approval.

**Pull request merged**
