### PR TITLE
[MGDCTRS-2112] - redirecting stderr to file in get-rhoc-connector-info script

### PR DESCRIPTION
**Pull request by tmielke**
Fixing [MGDCTRS-2112](https://issues.redhat.com//browse/MGDCTRS-2112). stderr output needs to be redirected to a file and not go into the pod's log.

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@pat-cremin can we get someone reviewing this PR ?

**Comment by supreeth7** [comment]
CI check failed:
```
10:06:11 In ./CEE/get-rhoc-connector-info/get-rhoc-connector-info.sh line 18:
10:06:11 NAMESPACED_NAMES=$(oc get pods --selector=cos.bf2.org/connector.id="${connector_id}" --all-namespaces -o jsonpath='{range .items[*]}{.metadata.namespace}{";"}{.metadata.name}{" "}{end}' 2> ${outputDir}/collect-namespaces.log)
10:06:11                                                                                                                                                                                              ^-- SC2086: Double quote to prevent globbing and word splitting.
```

**Pull request merged**
