### PR TITLE
Install python openshift-client

### PR DESCRIPTION
**Pull request by robshelly**
Install the python openshift-client which also requires an upgrade of pip to do so.

### CODE REVIEW

**Comment by georgettica** [comment]
Is tabulate also required for the openshift-cli ?
Or that required nonetheless

**Comment by reetika-vyas** [comment]
> Is tabulate also required for the openshift-cli ? Or that required nonetheless

I don't see any pre-requisite https://pypi.org/project/openshift-client/#:~:text=success%20or%20failure.-,Reader%20Prerequisites,-Familiarity%20with%20OpenShift

**Comment by vinaybommana** [comment]
Hi @reetika-vyas @wanghaoran1988 we are using tabulate for another managed-script in CSSRE - https://github.com/openshift/managed-scripts/tree/main/scripts/CSSRE/get-node-restarts

**Pull request merged**
