### PR TITLE
CSSRE-1942: add owners in CSSRE directory

### PR DESCRIPTION
**Pull request by vinaybommana**
As an SRE I want someone from my team specifically to review my PR in the managed backplane script repo (openshift/managed-scripts) so that I can make sure that I'm conforming to our conventions or patterns.

cc @pepedocs

### CODE REVIEW

**Comment by georgettica** [comment]
@vinaybommana could you sort this list?
that way if someone adds a duplicate it will be clear to see

and IMO it should always stay sorted :)

**Comment by vinaybommana** [comment]
sure georgettica.. I just added the reviewers based on the region
cc @pepedocs

**Comment by supreeth7** [comment]
@vinaybommana I can see that you are not a part of [OpenShift](https://github.com/openshift) org, could you make sure you're a part of it so it satisfies `/verify-owners`

**Comment by georgettica** [comment]
You can add comments and split the whole thing, but inside each section I would want it to be sorted

**Comment by georgettica** [comment]
You can also IIRC create groups in the owners in some fashion, so you could split it that way

**Comment by vinaybommana** [comment]
Hi @supreeth7 I'm not able to access `https://devservices.dpp.openshift.com/support/github_access_request/` url even with vpn to add request for joining in openshift org. I'm working on that, let me ping here when I'm done with that.

**Comment by vinaybommana** [comment]
@georgettica updated the owners list based on alphabetical order

**Comment by georgettica** [comment]
/approve
/lgtm

Can't attest this list is ok, but am fine with doing it this way and fixing if we need to :)

**Comment by georgettica** [comment]
Related to DPP-9848

**Pull request merged**
