### PR TITLE
Adding get rhosak operator script

### PR DESCRIPTION
**Pull request by R-Lawton**
Adding a script that uses oc adm inspect to get resources from RHOSAK operators.

### CODE REVIEW

**Comment by R-Lawton** [comment]
I dont think any RBAC is needed i was told users automatically have the cluster reader cluster role which has access to everything oc adm inspect needs

**Comment by R-Lawton** [comment]
Also i dont have access to see why the test failed

**Comment by wanghaoran1988** [comment]
```
01:30:44 [openshift-managed-scripts-gh-pr-check] $ /bin/sh -xe /tmp/jenkins9112491743154026141.sh
01:30:44 + ./hack/app_sre_pr_check.sh
01:30:44 ./hack/schema_validation.sh
01:30:44 convert ./scripts/CEE/check-tech-preview-features/metadata.yaml to json
01:30:44 convert succeed
01:30:44 convert ./scripts/CEE/etcd-health-check/metadata.yaml to json
01:30:44 convert succeed
01:30:44 convert ./scripts/CEE/get-kafka-instance-state/metadata.yaml to json
01:30:44 convert succeed
01:30:44 convert ./scripts/CEE/list-alerts/metadata.yaml to json
01:30:44 convert succeed
01:30:44 convert ./scripts/CEE/registry-s3-bucket-size/metadata.yaml to json
01:30:44 convert succeed
01:30:44 convert ./scripts/CEE/get-rhosak-operators/metadata.yaml to json
01:30:44 Traceback (most recent call last):
01:30:44   File "hack/yamltojson.py", line 4, in <module>
01:30:44     yaml_object = yaml.safe_load(yaml_in)
01:30:44   File "/usr/lib64/python3.6/site-packages/yaml/__init__.py", line 94, in safe_load
01:30:44     return load(stream, SafeLoader)
01:30:44   File "/usr/lib64/python3.6/site-packages/yaml/__init__.py", line 72, in load
01:30:44     return loader.get_single_data()
01:30:44   File "/usr/lib64/python3.6/site-packages/yaml/constructor.py", line 35, in get_single_data
01:30:44     node = self.get_single_node()
01:30:44   File "/usr/lib64/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
01:30:44     document = self.compose_document()
01:30:44   File "/usr/lib64/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
01:30:44     node = self.compose_node(None, None)
01:30:44   File "/usr/lib64/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
01:30:44     node = self.compose_mapping_node(anchor)
01:30:44   File "/usr/lib64/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
01:30:44     item_value = self.compose_node(node, item_key)
01:30:44   File "/usr/lib64/python3.6/site-packages/yaml/composer.py", line 82, in compose_node
01:30:44     node = self.compose_sequence_node(anchor)
01:30:44   File "/usr/lib64/python3.6/site-packages/yaml/composer.py", line 111, in compose_sequence_node
01:30:44     node.value.append(self.compose_node(node, index))
01:30:44   File "/usr/lib64/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
01:30:44     node = self.compose_mapping_node(anchor)
01:30:44   File "/usr/lib64/python3.6/site-packages/yaml/composer.py", line 127, in compose_mapping_node
01:30:44     while not self.check_event(MappingEndEvent):
01:30:44   File "/usr/lib64/python3.6/site-packages/yaml/parser.py", line 98, in check_event
01:30:44     self.current_event = self.state()
01:30:44   File "/usr/lib64/python3.6/site-packages/yaml/parser.py", line 439, in parse_block_mapping_key
01:30:44     "expected <block end>, but found %r" % token.id, token.start_mark)
01:30:44 yaml.parser.ParserError: while parsing a block mapping
01:30:44   in "./scripts/CEE/get-rhosak-operators/metadata.yaml", line 16, column 5
01:30:44 expected <block end>, but found '<scalar>'
01:30:44   in "./scripts/CEE/get-rhosak-operators/metadata.yaml", line 17, column 123
01:30:44 convert failed
01:30:44 make: *** [validation] Error 1
01:30:44 Build step 'Execute shell' marked build as failure
01:30:44 Setting status of 5ccbe258d8d15257b6150a9a0cae63f00c9addd2 to FAILURE with url https://ci.ext.devshift.net/job/openshift-managed-scripts-gh-pr-check/239/ and message: ' '
```

**Comment by wanghaoran1988** [comment]
```
20:15:14 In ./CEE/get-rhosak-operators/get-rhosak-operators.sh line 16:
20:15:14     oc adm inspect ns/redhat-kas-fleetshard-operator $sinceFlag --dest-dir $directory > "$directory"/rhosak.log 2>&1
20:15:14                                                      ^-- SC2128: Expanding an array without an index only gives the first element.
20:15:14                                                      ^-- SC2086: Double quote to prevent globbing and word splitting.
20:15:14                                                                            ^-- SC2086: Double quote to prevent globbing and word splitting.
20:15:14 
20:15:14 
20:15:14 In ./CEE/get-rhosak-operators/get-rhosak-operators.sh line 19:
20:15:14     oc adm inspect ns/managed-application-services-observability $sinceFlag --dest-dir $directory > "$directory"/rhosak.log 2>&1
20:15:14                                                                  ^-- SC2128: Expanding an array without an index only gives the first element.
20:15:14                                                                  ^-- SC2086: Double quote to prevent globbing and word splitting.
20:15:14                                                                                        ^-- SC2086: Double quote to prevent globbing and word splitting.
20:15:14 
20:15:14 
20:15:14 In ./CEE/get-rhosak-operators/get-rhosak-operators.sh line 22:
20:15:14     oc adm inspect  ns/redhat-managed-kafka-operator --dest-dir $directory > "$directory"/rhosak.log 2>&1
20:15:14                                                                 ^-- SC2086: Double quote to prevent globbing and word splitting.
20:15:14 
20:15:14 
20:15:14 In ./CEE/get-rhosak-operators/get-rhosak-operators.sh line 31:
20:15:14     tar -zcf  $directory.tar.gz ./"$directory"
20:15:14               ^-- SC2086: Double quote to prevent globbing and word splitting.
20:15:14 
```

**Comment by R-Lawton** [comment]
Thank you @wanghaoran1988 for the screenshots im in the process of getting access will let you know when i get it

**Comment by reetika-vyas** [comment]
Build is successful
```
16:43:41 [openshift-managed-scripts-gh-pr-check] $ /bin/sh -xe /tmp/jenkins7298447734980922126.sh
16:43:42 + '[' -z '' ']'
16:43:42 + exit
16:43:42 Setting status of 02ad8afc4a8d7a3fbd227c7f8a3fe7ee2b8f5a27 to SUCCESS with url https://ci.ext.devshift.net/job/openshift-managed-scripts-gh-pr-check/244/ and message: ' '
16:43:42 Using context: ci.ext.devshift.net PR build
16:43:42 Finished: SUCCESS
```

**Pull request merged**
